boostorg/config

include/boost/cstdint.hpp
Full warning:
".../boost/cstdint.hpp:504:77: warning: backslash and newline separated by space
(defined(_ULLONG_MAX) && _ULLONG_MAX == 18446744073709551615ULL) || \ "
=> Remove trailing whitespace to avoid gcc warning

checks/architecture/32.cpp, checks/architecture/64.cpp, checks/architecture/Jamroot.jam, checks/architecture/arm.cpp, checks/architecture/combined.cpp, checks/architecture/mips1.cpp, checks/architecture/power.cpp, checks/architecture/sparc.cpp, checks/architecture/x86.cpp
Part of a patch set from @vprus for fixing https://svn.boost.org/trac/boost/ticket/10858
This patch add the detection logic removed from Boost.Context here.
=> Lift architecture detection

include/boost/config/compiler/visualc.hpp
- C++ 14 digit separators were implemented in CTP5:
https://www.visualstudio.com/en-us/news/vs2015-vs.aspx#vcplus
- the value initialization bugs have been fixed:
http://www.boost.org/development/tests/develop/developer/output/teeks99-08f-win2012R2-64on64-boost-bin-v2-libs-utility-test-value_init_workaround_test-test-msvc-14-0-dbg-adrs-mdl-64-thrd-mlt.html
Both tests are passing now.
=> Update for MSVC 14 CTP 6

test/boost_no_constexpr.ipp
MSVC 14 RC currently passes the constexpr tests, but fails to compile Boost if BOOST_NO_CXX11_CONSTEXPR is not defined. Added three tests that clang can compile in C++11 mode, but MSVC cannot.
=> Add more constexpr tests

test/boost_no_constexpr.ipp
MSVC 14 RC doesn't call the constexpr conversion operator in some cases.
It complains:
boost_no_constexpr.ipp(72): error C2051: case expression not constant
=> Add another constexpr test

include/boost/config/compiler/xlcpp.hpp, include/boost/config/select_compiler_config.hpp
adding a toolset 'xlcpp' for the new IBM compilers based on clang, old toolset 'vacpp' will remain for older IBM compilers not based on clang
=> adding toolset for xlcpp

include/boost/config/compiler/visualc.hpp
Now that the final version has been released, I don't think the warning spam for every compiler update is necessary anymore. Boost builds successfully with the RTM version (except for Locale, which doesn't build at all currently).
=> Update for VS 2015 RTM

include/boost/config/stdlib/dinkumware.hpp
As mentioned by Stephan T. Lavavej here:
http://lists.boost.org/Archives/boost/2014/11/217698.php
BOOST_NO_CXX11_ADDRESSOF shouldn't be necessary anymore for MSVC 14 RTM. The unit test passes.
=> Update for the VS14 RTM standard library

include/boost/config/stdlib/dinkumware.hpp
If _HAS_AUTO_PTR_ETC is defined to 0, MSVC14's standard library implements C++17's N4190, thus removing std::auto_ptr.
=> Update for MSVC14's _HAS_AUTO_PTR_ETC

include/boost/config/platform/cloudabi.hpp, include/boost/config/select_platform_config.hpp
Nuxi CloudABI is a POSIX-like runtime environment purely built on the
principle of capability-based security[1]. It allows you to run
arbitrary untrusted binaries directly on top of a UNIX kernel without
compromising system integrity.
This change adds a basic platform configuration that defines a small set
of options that allow it to build most of the Boost sources. The next
step is to send out small fixes to individual libraries that don't build
yet.
[1] Nuxi CloudABI: https://github.com/NuxiNL/cloudlibc
=> Add basic platform bits for Nuxi CloudABI.

include/boost/config/compiler/clang.hpp
Clang has supported the 'unused' attribute since the first release.
=> Remove the detection code for 'unused' attribute on Clang

include/boost/config/compiler/clang.hpp, include/boost/config/compiler/gcc.hpp
Both gcc and clang (since their early versions like gcc-2.9.5 and clang-1.0) accept attribute names with double underscores to avoid macro interference. So it's better to guard attribute names with double underscores, but there are unguarded ones in `clang.hpp` and `gcc.hpp`: 
```
```
This PR fix this.
=> Guard attribute names with double underscores

include/boost/config/platform/win32.hpp
(This is a similar PR as https://github.com/boostorg/config/pull/16 but with the difference that it doesn't pull in a dependency on Boost.Predef)
When targeting WinRT (phone, store, universal) we do not want to use ANSI versions of Windows APIS as a lot of the old win32 ansi apis are missing, therefore let's skip them altogether.
=> Do not use Windows ANSI APIs when targetting WinRT

include/boost/config/compiler/clang.hpp, include/boost/config/compiler/gcc.hpp, include/boost/config/compiler/intel.hpp
Fix trac issue
https://svn.boost.org/trac/boost/ticket/11852
Similar to
https://svn.boost.org/trac/boost/ticket/8048
`__float128` is still unsupported when compiling with nvcc *in non-C++11 mode* (tested with `CUDA 7.5.18`). First noticed with the latest release (`1.60.0`) and `GCC 4.8.5` but should affect all previous releases depending on used modules.
~~In my case, I triggered it with the components
`program_options regex filesystem system thread math_tr1`
enabled.~~
The reason this is triggered in headers is that `boost 1.60.0` introduced `__float128` type traits in [type_traits/is_floating_point.hpp](https://github.com/boostorg/type_traits/blob/boost-1.60.0/include/boost/type_traits/is_floating_point.hpp#L24-L26) which were not implemented in the previous release …
=> Fix Trac 11852: CUDA in C++03 Mode and __float128

include/boost/config/suffix.hpp
__has_attribute to be used instead of __has_cpp_attribute, not remove the functionality.
=> For Oracle Developer Studio

include/boost/config/stdlib/libcpp.hpp
Make sure that BOOST_NO_CXX17_STD_INVOKE is defined for C++03/11/14 builds.
=> BOOST_NO_CXX17_STD_INVOKE for libc++

include/boost/config/compiler/visualc.hpp
- Aggregate NSDMI and relaxed constexpr are supported
- _MSC_VER is 1910
All Config tests are passing and all projects using Boost I have access to compile and run fine.
=> Update for Visual Studio 15 Preview 5

.gitignore
Ignores files under
checks/architecture/bin
In order to maintain a clean tree after builds.
=> Adds .gitignore to prevent tracking changes of binary compiled files.

include/boost/config/compiler/intel.hpp
Intel compiler up to version 17.0 (on Linux) makes constexpr member functions implicitly const-qualified.
This PR is a continuation of https://github.com/boostorg/config/pull/104 and http://lists.boost.org/Archives/boost/2016/12/231859.php.
=> Disable C++14 constexpr for Intel compiler

include/boost/config/compiler/intel.hpp
- Define BOOST_NO_CXX14_CONSTEXPR only for the gcc-compatible version of Intel compiler (other versions untested). The previous definition was not in the correct preprocessor branch and the macro was not defined when it should have been.
- Increased the latest tested Intel compiler version to 17.
- Added comments to the preprocessor directives to simplify navigation in the file.
=> Move BOOST_NO_CXX14_CONSTEXPR to the right section

include/boost/detail/workaround.hpp
BOOST_GCC is absent among the convenience guards present for BOOST_WORKAROUND.
=> Support BOOST_GCC guards in BOOST_WORKAROUND

include/boost/config/auto_link.hpp
Boost built with MS VS 2017 RC has -vc150 suffix.
=> Use corrent name for libraries built with MS VS 2017 RC.

doc/macro_reference.qbk, include/boost/config/suffix.hpp
Provide support for :+1: 
- portable restrict kywrod as BOST_RESTRICT
- indicator to check i restrict can or can not be applied to references
=> Provide BOOST_RESTRICT and BOOST_NO_RESTRICT_REFERENCES

include/boost/config/compiler/clang.hpp
In Clang/C2, __builtin_expect is defined. But using __builtin_expect end up with an compiler internal error. Use _MSC_VER to detect it's in Clang/C2, and ignore the __builtin_expect.
=> Fix a compiling problem under Clang/C2.

test/boost_no_cxx11_sfinae_expr.ipp
Will now compile-fail for Intel C++ 13 instead of run-fail.
=> Update boost_no_cxx11_sfinae_expr test to fail faster

include/boost/config/compiler/clang.hpp
When compiling in pre-C++11 clang mode it should be defined
=> Define BOOST_NO_CXX11_SFINAE_EXPR in C++98 clang

include/boost/detail/workaround.hpp
I'd missed workaround.hpp. And since `__IBMCPP__` doesn't uniquely identify the z/OS compiler, I guess there should be a `_WORKAROUND_GUARD` for `BOOST_XLCPP_ZOS`...
Is there anything else that needs to be done for `BOOST_WORKAROUND()` support?
=> add _WORKAROUND_GUARD macros for BOOST_XLCPP_ZOS

include/boost/config/auto_link.hpp
This PR should *not* be accepted unless the [community consensus on the mailing list](http://lists.boost.org/Archives/boost/2017/03/233543.php) converges around option 2.
=> Using 141 instead of 1410

doc/html/boost_config/boost_macro_reference.html, doc/macro_reference.qbk, include/boost/config/stdlib/dinkumware.hpp
The algorithm std::random_shuffle was marked as deprecated in C++14 and is removed from the upcoming C++17 standard. The name itself is still reserved and library implementations may continue to ship it. In this sense, support for std::random_shuffle must be regarded as purely optional and a feature-test macro is required to test for its presence.
Signed-off-by: Daniela Engert <dani@ngrt.de>
=> Introduce feature-test macro BOOST_NO_CXX17_STD_RANDOM_SHUFFLE

include/boost/config/stdlib/libcpp.hpp
New libc++ versions remove `std::auto_ptr` when building as C++17, unless the magic tag `_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR` is defined. Tell the rest of Boost that there's no `auto_ptr` in that case.
=> define BOOST_NO_AUTO_PTR when building with libc++ and C++17

include/boost/config/compiler/cray.hpp
config/cray.hpp updated for release 8.6 of CCE (Cray Compiler Environ…
…ment)
The default C++ standard support at this release is c++14, compared
with c++03 in previous releases.
=> Cray compiler config update to support current release and c++14.

include/boost/config/compiler/cray.hpp
Further updates to support C++03 C++11 and C++14 and releases 8.5 and 8.6 of the cray C++ compiler.
=> Cce86 cray config

test/link/bc_gen.sh, test/link/vc_gen.sh
"/bin/bash" is a Linuxism.  "/usr/bin/env bash" is portable.
=> Fix bash paths in shebangs

include/boost/cstdint.hpp
Remove an old PGI-specific workaround for intptr_t.  The workaround is no longer necessary and now causes compilation errors.
=> Update PGI C++ compiler support

include/boost/config/compiler/visualc.hpp
I know, Boost doesn't support MSVC 5.0 and 6.0. But the expression is invalid. Another way to fix it is
```c++
// Note: Versions up to 7.0 aren't supported.
```
=> Incorrect MSVC version detection

include/boost/config/compiler/visualc.hpp
Update the version number to VS2017.3's.
=> Update last known MSVC version to 19.11.25506 (VS2017.3).

include/boost/config/compiler/visualc.hpp
Both config tests pass with /std:c++14 as well as /std:c++17.
=> MSVC: 14.11 supports structured bindings in C++17 mode

.travis.yml, doc/html/boost_config/acknowledgements.html, doc/html/boost_config/boost_macro_reference.html, doc/html/boost_config/build_config.html, doc/html/boost_config/cstdint.html, doc/html/boost_config/guidelines_for_boost_authors.html, doc/html/boost_config/rationale.html, doc/html/index.html, doc/macro_reference.qbk, include/boost/config/detail/suffix.hpp, include/boost/config/helper_macros.hpp, include/boost/config/pragma_message.hpp, test/Jamfile.v2, test/helper_macros_test.cpp, test/pragma_message_test.cpp
This PR adds `BOOST_PRAGMA_MESSAGE(M)`, a macro that expands to an equivalent on `#pragma message(M)`, when it's supported. In addition, on MSVC it adds `__FILE__` and `__LINE__` to the message, as the plain `#pragma message` has the problem that it's impossible to tell where the message originated.
Since there are places where Boost.Config itself emits messages using the preprocessor, the best place for this utility macro is in Config so that it can be used inside.
This PR includes #194. Also includes a few unrelated doc fixes and regenerates the HTML.
=> Add BOOST_PRAGMA_MESSAGE

include/boost/config/compiler/gcc.hpp
The are only two uses of BOOST_NO_CXX14_VARIABLE_TEMPLATES in Boost right now: Boost.Align (for alignment_of only) and Boost.TypeTraits (for the detection idiom toolkit only), so this should have minimal impact.
=> Variable templates are somewhat unusable in GCC 5.1 (bug 65719)

include/boost/config/compiler/intel.hpp
Also, this doesn't fix it, but apparently intel compilers don't support `__attribute__((fallthrough))` but BOOST_FALLTHROUGH is defined by the gcc config, according to the beast test results:
http://www.boost.org/development/tests/master/developer/output/intel-linux-master-boost-bin-v2-libs-beast-test-beast-websocket-accept-test-intel-linux-linux-debug-threadapi-pthread-threading-multi.html
=> Undefine BOOST_GCC for intel compilers

include/boost/config/compiler/clang.hpp, include/boost/config/compiler/gcc.hpp
This is required at least for Boost.WinAPI to match the declarations in
Windows SDK headers, which use dllimport.
Also, for clang on Windows, use dllimport/dllexport even beyond Cygwin.
The compiler does support these attributes, and it should for
compatibility with Windows headers.
=> Use dllimport/dllexport with clang and gcc on Cygwin.

include/boost/config/compiler/nvcc.hpp
Expressions like `BOOST_CUDA_VERSION / 1000000` don't work correctly; add parentheses around the expression to fix.
=> Add parentheses to BOOST_CUDA_VERSION

include/boost/config/platform/cygwin.hpp
I tested this in a private build on AppVeyor CI against numeric/interval where the problem originally surfaced.  This build job failed without the change:
https://ci.appveyor.com/project/jeking3/interval/builds/19983035/job/9glx1bs1r28a421l
Ref:
https://github.com/Alexpux/Cygwin/commit/0f81b5d4bcaa5c840031796d94df9ba6d6fae4d0#diff-447ff859802166057451911061326417R390
Thanks.
=> Fix BOOST_NO_FENV_H on cygwin (it exists since 2010...)

include/boost/config/compiler/clang.hpp
See https://github.com/boostorg/math/issues/181
=> Tentatively enable __float128 support for clang

include/boost/config/compiler/gcc.hpp
=> __builtin_unreachable was introduced in GCC 4.5

include/boost/config/compiler/gcc.hpp
The problem seems affect only 32bit compilers. See https://sourceforge.net/p/mingw-w64/bugs/527/#cedc.
ref https://github.com/boostorg/config/commit/fe5e07b521e49f6cca712c801e025fed13c23979#commitcomment-32969838
=> Lift thread local ban for 64bit MinGW

appveyor.yml, include/boost/config/auto_link.hpp
Also added two build jobs for toolset clang-win on Appveyor.
This fixes https://github.com/boostorg/uuid/issues/78
=> Enable auto link support for clang on windows (clang-win) (clang-cl)

doc/macro_reference.qbk, include/boost/config/detail/suffix.hpp
The `BOOST_INLINE_VARIABLE` macro can be used to mark C++17 inline variables in contexts where omitting the `inline` keyword is still acceptable on older compilers.
A few use cases:
https://github.com/boostorg/atomic/blob/fc410975146a23e0513e8164009cc1eac2d9830b/include/boost/memory_order.hpp#L57
https://github.com/boostorg/core/issues/63
https://github.com/boostorg/optional/issues/33
This commit also adds the missing docs for `BOOST_NO_CXX17_INLINE_VARIABLES`.
=> Add BOOST_INLINE_VARIABLE macro

CMakeLists.txt
This is necessary, because for a library to have install support, all the dependencies need to have it, and Config is a dependency of pretty much everything.
=> Update CMakeLists.txt with install support

doc/guidelines.qbk
The macro __linux is less portable and, for example, is not defined on
some architectures.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=28314.
=> Use __linux__ instead of __linux.

checks/architecture/mips1.cpp
currently mips1.cpp can only recognize mips 32bit (MIPS1 by __mips=1,
and mips2 above by R3000).
64bit cannot be recognized.
So drop the __mips==1 here.
=> make mips1.cpp recognize all mips

include/boost/config/compiler/gcc.hpp, test/boost_no_cxx11_alignas.ipp
gcc 4.8 [appears](https://travis-ci.org/boostorg/atomic/jobs/656805795#L870) to not support `alignas` specifier with a constant expression as an argument. This PR updates the test to detect this and increases gcc version to 4.9.
=> Increase gcc version for BOOST_NO_CXX11_ALIGNAS to 4.9

include/boost/config/auto_link.hpp
Check for `BOOST_AUTO_LINK_NOMANGLE` before any other layouts.
This way, `BOOST_AUTO_LINK_NOMANGLE` can be defined temporarily to link
to non-Boost libraries even if `BOOST_AUTO_LINK_TAGGED` or
`BOOST_AUTO_LINK_SYSTEM` are defined.
Boost.UUID does this:
https://github.com/boostorg/uuid/blob/24e3e0db36adfae963c9fc523d0d1e3b1f171950/include/boost/uuid/detail/random_provider_bcrypt.ipp#L20
https://github.com/boostorg/uuid/blob/24e3e0db36adfae963c9fc523d0d1e3b1f171950/include/boost/uuid/detail/random_provider_wincrypt.ipp#L24
=> Support auto-linking for non-Boost libraries

include/boost/config/compiler/codegear.hpp, include/boost/config/detail/suffix.hpp, include/boost/config/stdlib/dinkumware.hpp, test/boost_no_cwchar.ipp
I discovered through testing some issues and made further changes to the Embarcadero C++ clang-based compilers support in config. I also updated the test for support of the cwchars header file involving a basic test for multi-byte character support in the header file. The Embarcadero C++ clang-based compilers were passing the test but were actually missing all the multi-byte support in the header file, including all wide character to multi-byte and all the multi-byte to wide character functionality in the header file. So I felt updating the test slightly just to make sure that multi-byte support existed in its most basic form was necessary. I do not think this will affect any other compilers, and in my testing all the compilers I tested were not affected in any way by failing the test …
=> Further changes for Embarcadero C++ clang-based compilers

checks/config.jam
This PR removes the "Boost.Config Feature Check:" prefix from the feature check messages. It's repetitive, takes up horizontal space, and the messages are still clear enough without it.
=> Remove prefix from feature check messages

include/boost/config/stdlib/libstdcpp3.hpp
They are not available from libstdc++ in that case. This has been the case since 2007 ([see GCC commit, in libstdc++-v3/include/bits/stl_function.h](https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=40abbf1f1737b16b1ae6a8d8094e825f6a3b41f2)). I've only added the define to the _GLIBCXX_USE_DEPRECATED branch, because that is the only define checked in the original GCC commit.
With this change Boost builds correctly with _GLIBCXX_USE_DEPRECATED=0.
=> Do not use C++98 binders when _GLIBCXX_USE_DEPRECATED=0

include/boost/config/compiler/gcc.hpp, test/boost_no_cxx11_alignas.ipp
Closes https://github.com/boostorg/config/issues/358.
=> Update the test for C++11 alignas to trigger failure on gcc 4.8

include/boost/config/stdlib/libstdcpp3.hpp
This restriction is either too pessimistic or completely wrong.
Closes #367
=> Remove BOOST_NO_CXX11_HDR_ATOMIC for Clang < 3.7

include/boost/config/compiler/common_edg.hpp
This PR adds some feature test macros for the C++11 features.  I wasn't sure about decltype, so left that as-is for now, but documented what the appropriate check should be.
=> Add feature test macros for C++11 features.

include/boost/config/auto_link.hpp
None of the other toolset names include a 32/64-bit indicator. Remove the `32`/`64` and change the name to `embtc` to match with boostorg/build#675, so that auto-linking actually works.
=> Don't add address model in Embarcadero toolset name

include/boost/config/compiler/gcc.hpp
This was fixed in gcc 11, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83562
=> Allow thread_local on mingw with gcc>=11

test/boost_no_ctype_functions.ipp
See https://github.com/boostorg/config/issues/382.
=> Correct boost_no_ctype_functions.ipp for C++20.

include/boost/config/detail/suffix.hpp
Fixes https://github.com/boostorg/config/issues/392.
=> Patch for noinline attribute on the HIP compiler.

include/boost/config/detail/suffix.hpp, test/helper_macro_test.cpp
It's not supported on functions pre-c++11 even if __has_cpp_attribute indicates it is supported.
Also update test case.
Fixes https://github.com/boostorg/config/issues/336.
=> Update nodiscard attribute:

include/boost/config/stdlib/libstdcpp3.hpp
Fixes: https://github.com/boostorg/container_hash/issues/22.
=> Define BOOST_NO_CXX98_FUNCTION_BASE for gcc-12 in C++17 mode or later.

doc/macro_reference.qbk, include/boost/config/detail/suffix.hpp, test/helper_macro_test.cpp
Compilers and static analysis tools have started warning on the use of integral null pointer constants, suggesting that they need to be replaced with `nullptr`. This leads to people submitting pull requests that replace the uses of `0` with `nullptr`, such as for example https://github.com/boostorg/throw_exception/pull/22 (https://github.com/boostorg/throw_exception/pull/22/commits/8678b7cb09ad71bffbc24b099fc2a86bd925046a). However, `nullptr` is not available in C++03, which necessitates checking `BOOST_NO_CXX11_NULLPTR` as in https://github.com/boostorg/throw_exception/pull/22/commits/0a752cc9f87be1faaf8d7adcbc2cf4220623fbc1.
The proposed helper macro `BOOST_NULLPTR` expands to `nullptr` when it's supported, `0` otherwise, which avoids the need to check `BOOST_NO_CXX11_NULLPTR` in …
=> Add BOOST_NULLPTR helper macro

doc/macro_reference.qbk, include/boost/config/compiler/clang.hpp, include/boost/config/compiler/gcc.hpp, include/boost/config/compiler/sunpro_cc.hpp, include/boost/config/compiler/visualc.hpp, include/boost/config/compiler/xlcpp.hpp, include/boost/config/detail/suffix.hpp, include/boost/config/header_deprecated.hpp, test/Jamfile.v2, test/symbol_deprecated_test.cpp
`BOOST_DEPRECATED` can be used to mark functions, types and objects as deprecated, with a message with a recommendation of replacement. Using such marked symbols in code will generate compiler warnings, with the
specified message, if possible.
The warnings can be suppressed if `BOOST_ALLOW_DEPRECATED_SYMBOLS` is defined. Additionally, added support `BOOST_ALLOW_DEPRECATED` macro that not only allows for deprecated symbols but also deprecated headers (i.e. defining
`BOOST_ALLOW_DEPRECATED` is equivalent to defining both `BOOST_ALLOW_DEPRECATED_SYMBOLS` and `BOOST_ALLOW_DEPRECATED_HEADERS`).
Closes https://github.com/boostorg/config/issues/280.
=> Add a BOOST_DEPRECATED macro for deprecated symbol markup

.github/workflows/ci.yml, include/boost/config/stdlib/libstdcpp3.hpp
Fixes: https://github.com/boostorg/config/issues/399.
=> GNU libstdc++3 _GTHREAD_USE_MUTEX_TIMEDLOCK is not used post gcc-6.

include/boost/config/stdlib/libstdcpp3.hpp
See https://github.com/boostorg/type_traits/pull/176#issuecomment-1304871472
=> Fix -Wundef for `_GLIBCXX_USE_DEPRECATED` on libstdc++ >= 4.6

include/boost/config/detail/suffix.hpp
When available, supersedes: https://github.com/boostorg/config/pull/456
=> Expand BOOST_ATTRIBUTE_UNUSED [[maybe_unused]]

include/boost/config/stdlib/libstdcpp3.hpp
To determine libstdc++ version.
Fixes https://github.com/boostorg/config/issues/455
=> Clang should use _GLIBCXX_RELEASE

checks/architecture/Jamfile.jam, checks/architecture/loongarch.cpp
=> Add support for LoongArch

include/boost/config/compiler/clang_version.hpp
…since `__APPLE__` is defined by both Apple Clang and LLVM.org Clang on Apple platforms (as mentioned by https://github.com/boostorg/config/pull/39#issuecomment-59946538).
This ensures `BOOST_CLANG_VERSION` is defined correctly when using LLVM.org clang.
| Compiler               | Before | After  |
|------------------------|--------|--------|
| Xcode 14.2 Apple Clang | `140000` | `140000` |
| LLVM.org Clang 17.0.3  | `140000` | `170003` |
| LLVM.org Clang 9.0.1   | `40000`  | `90001`  |
=> Use `__apple_build_version__` to detect Apple clang

.github/workflows/ci.yml
msvc-14.0 doesn't have `/std:c++17`, only `/std:c++latest`, so the `cxxstd=17` job did nothing.
While here I also added 20 to msvc-14.2 and msvc-14.3, because they support that now.
=> Update cxxstd values for GHA msvc jobs
