boostorg/config

include/boost/config/platform/haiku.hpp
- Fixes the functional/hash library
- Fixes problems with the thread library
=> Haiku: remove invalid feature definitions

include/boost/config/compiler/visualc.hpp
Looking at STL's list, I didn't see anything else requiring Boost.Config changes.
See http://blogs.msdn.com/b/vcblog/archive/2015/04/29/c-11-14-17-features-in-vs-2015-rc.aspx
--Beman
=> Update version check for VisualStudio 2015 RC.

test/boost_no_cxx14_constexpr.ipp
This PR updates a config_test regarding http://lists.boost.org/Archives/boost/2016/12/231859.php .
Tested:
- GCC 6.2.1 20160916 (Fedora Rawhide)
- gnu++98, gnu++11, gnu++14
- Clang 3.9.0 (Fedora Rawhide)
- gnu++98, gnu++11, gnu++14
=> Update c++14 constexpr test.

include/boost/config/stdlib/dinkumware.hpp
Signed-off-by: Daniela Engert <dani@ngrt.de>
=> vc++ 19.10 has std::apply if enabled by /std:c++latest

test/boost_no_cxx11_thread_local.ipp
Try to reproduce issues:
https://github.com/libbitcoin/libbitcoin/issues/733#issuecomment-301652210
https://github.com/boostorg/multiprecision/issues/20
=> Enhance thread_local tests.

include/boost/config/compiler/gcc.hpp
=> Add BOOST_FALLTHROUGH for gcc

include/boost/version.hpp
=> Bump version number to 1.66

include/boost/config/auto_link.hpp
This corresponds to the superproject PR boostorg/boost#149 and should be applied in tandem with it.
=>  Use architecture and address model in autolink

include/boost/config/compiler/visualc.hpp
This to get ride of this error:
Unknown compiler version - please run the configure tests and report the results
=> Update to newest Visual Studio 2017

.travis.yml, CMakeLists.txt, test/cmake/CMakeLists.txt, test/cmake/main.cpp
For further reference: https://groups.google.com/forum/#!topic/boost-developers-archive/kM4JRmyVl3M
=> [CMake] Generate cmake target for boost config that other libraries can depend on

doc/macro_reference.qbk, include/boost/config/detail/suffix.hpp, test/helper_macro_test.cpp
See https://github.com/boostorg/config/issues/257.
=> Add BOOST_ATTRIBUTE_NO_UNIQUE_ADDRESS.

checks/architecture/Jamroot.jam, checks/architecture/s390.cpp
Include s390x as a supported architecture
=> Add support for s390x

include/boost/version.hpp
Looks like I should have made this PR to master when I did develop.
=> bump version for 1.72

include/boost/config/detail/suffix.hpp
=> fixes warning in clang-6

.travis.yml
See https://github.com/boostorg/math/issues/272.
=> Add gcc-5 gnu-mode tests.

.github/workflows/ci.yml, include/boost/config/stdlib/libcpp.hpp
Also adds more comprehensive msvc-14.x testing.
=> Add GHA to get XCode-12 testing.

include/boost/config/stdlib/libstdcpp3.hpp
Fixes: https://github.com/boostorg/config/issues/376.
=> Tentative fix for issue 376.

include/boost/config/platform/bsd.hpp
=> Config: Update bits for OpenBSD

include/boost/config/workaround.hpp
This should resolve https://github.com/boostorg/config/issues/322 and (partially) https://github.com/boostorg/type_traits/issues/107.
=> Define __clang_major___WORKAROUND_GUARD

include/boost/detail/workaround.hpp
This resolves https://github.com/boostorg/config/issues/381.
=> Update detail/workaround.hpp include guard

.github/workflows/ci.yml, include/boost/config/platform/wasm.hpp
Fixes https://github.com/boostorg/config/issues/402.
=> Tentatively add emscripten testing and support.

checks/architecture/Jamfile.jam, checks/architecture/mips.cpp
=> Rename mips1 to mips and alias mips1 to mips

.drone.star, .github/workflows/ci.yml
Reduce when Github jobs are run.
=> Remove no longer supported XCode versions.

.drone.star, include/boost/config/stdlib/libstdcpp3.hpp
Refs https://github.com/boostorg/config/issues/462.
=> Add XCode 9.4.1 testing.

.github/workflows/ci.yml, include/boost/config/compiler/visualc.hpp
Fixes: https://github.com/boostorg/serialization/issues/271
Also removes failing cuda+clang test as it's an inscrutable system setup issue.
=> Add msvc support for [[maybe_unused]] attribute.
